export const ranks = [
  { name: 'Nobel Laureate', color: '#FFD700', emoji: '🥇', req: 100000 },
  { name: 'Quantum Overlord', color: '#9F7AEA', emoji: '🌌', req: 75000 },
  { name: 'Elemental Deity', color: '#E53E3E', emoji: '⚡', req: 50000 },
  { name: 'Molecular Mastermind', color: '#3182CE', emoji: '🧠', req: 40000 },
  { name: 'Alchemist Supreme', color: '#D69E2E', emoji: '🔮', req: 30000 },
  { name: 'Catalyst Commander', color: '#38A169', emoji: '💥', req: 25000 },
  { name: 'Atomic Architect', color: '#00B5D8', emoji: '⚛️', req: 20000 },
  { name: 'Synthesizer Prime', color: '#D53F8C', emoji: '🧬', req: 18000 },
  { name: 'Isotope Innovator', color: '#805AD5', emoji: '☢️', req: 16000 },
  { name: 'Reaction Royalty', color: '#E53E3E', emoji: '👑', req: 14000 },
  { name: 'Crystal Connoisseur', color: '#38B2AC', emoji: '💎', req: 12000 },
  { name: 'Titration Titan', color: '#319795', emoji: '💧', req: 10000 },
  { name: 'Plasma Pioneer', color: '#DD6B20', emoji: '🔥', req: 9000 },
  { name: 'Neutron Navigator', color: '#4A5568', emoji: '🧭', req: 8000 },
  { name: 'Orbital Observer', color: '#2B6CB0', emoji: '🪐', req: 7000 },
  { name: 'Bond Breaker', color: '#C53030', emoji: '🔨', req: 6500 },
  { name: 'Solution Sorcerer', color: '#805AD5', emoji: '🪄', req: 6000 },
  { name: 'Spectrum Scholar', color: '#ED8936', emoji: '🌈', req: 5500 },
  { name: 'Kinetic King', color: '#38A169', emoji: '🏃‍♂️', req: 5000 },
  { name: 'Thermodynamic Thinker', color: '#E53E3E', emoji: '🌡️', req: 4500 },
  { name: 'Compound Creator', color: '#00A3C4', emoji: '🏗️', req: 4000 },
  { name: 'Reagent Ranger', color: '#3182CE', emoji: '🤠', req: 3500 },
  { name: 'Electron Enthusiast', color: '#ECC94B', emoji: '⚡', req: 3200 },
  { name: 'Nucleus Ninja', color: '#1A202C', emoji: '🥷', req: 2900 },
  { name: 'Polymer Prodigy', color: '#D53F8C', emoji: '🔗', req: 2600 },
  { name: 'Matrix Magician', color: '#9F7AEA', emoji: '🎩', req: 2400 },
  { name: 'Flask Fanatic', color: '#38B2AC', emoji: '🏺', req: 2200 },
  { name: 'Beaker Baron', color: '#2F855A', emoji: '🍺', req: 2000 },
  { name: 'Solvent Sultan', color: '#2C5282', emoji: '🌊', req: 1800 },
  { name: 'Precipitate Prince', color: '#C05621', emoji: '❄️', req: 1600 },
  { name: 'Acid Ace', color: '#E53E3E', emoji: '🍋', req: 1400 },
  { name: 'Base Boss', color: '#2B6CB0', emoji: '🧼', req: 1200 },
  { name: 'Buffer Baron', color: '#4A5568', emoji: '🛡️', req: 1100 },
  { name: 'Molecule Molder', color: '#805AD5', emoji: '👐', req: 1000 },
  { name: 'Distillation Duke', color: '#319795', emoji: '♨️', req: 900 },
  { name: 'Filtration Fiend', color: '#718096', emoji: '☕', req: 800 },
  { name: 'Chromatography Champ', color: '#DD6B20', emoji: '📜', req: 700 },
  { name: 'Spectral Sleuth', color: '#3182CE', emoji: '🕵️', req: 650 },
  { name: 'Quantum Quester', color: '#9F7AEA', emoji: '🌠', req: 600 },
  { name: 'Lab Legend', color: '#805AD5', emoji: '🏆', req: 500 },
  { name: 'Bunsen Burner Boss', color: '#E53E3E', emoji: '🔥', req: 450 },
  { name: 'Pipette Paladin', color: '#38A169', emoji: '💉', req: 400 },
  { name: 'Goggle Guru', color: '#00B5D8', emoji: '🥽', req: 350 },
  { name: 'Mad Scientist', color: '#DD6B20', emoji: '🧑‍🔬', req: 300 },
  { name: 'Vial Veteran', color: '#319795', emoji: '🫙', req: 260 },
  { name: 'Test Tube Tactician', color: '#2B6CB0', emoji: '🧪', req: 220 },
  { name: 'Centrifuge Cyclone', color: '#4A5568', emoji: '🌪️', req: 180 },
  { name: 'Chemical Warrior', color: '#3182CE', emoji: '⚔️', req: 150 },
  { name: 'Safety Supervisor', color: '#ECC94B', emoji: '🦺', req: 120 },
  { name: 'Gloves Gladiator', color: '#805AD5', emoji: '🧤', req: 100 },
  { name: 'Scale Specialist', color: '#718096', emoji: '⚖️', req: 80 },
  { name: 'Beaker Breaker', color: '#38A169', emoji: '🧪', req: 50 },
  { name: 'Hood Hopper', color: '#2C5282', emoji: '💨', req: 40 },
  { name: 'Magnetic Stirrer', color: '#E53E3E', emoji: '🌀', req: 30 },
  { name: 'Lab Assistant', color: '#D69E2E', emoji: '📋', req: 20 },
  { name: 'Lab Rat', color: '#718096', emoji: '🐀', req: 10 },
  { name: 'Dish Washer', color: '#A0AEC0', emoji: '🧽', req: 5 },
  { name: 'Baby Chemist', color: '#CBD5E0', emoji: '🍼', req: 0 }
];

export const getRankByPoints = (points, customTitle) => {
  let highestRank = ranks.find(r => points >= r.req);
  if (customTitle) {
    const customRank = ranks.find(r => r.name === customTitle && points >= r.req);
    if (customRank) return customRank;
  }
  return highestRank || ranks[ranks.length - 1];
};
